spring:
  datasource:
    name: redpackage
    url: jdbc:mysql://localhost:3306/example
    username: root
    password: root
# 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
#配置mapper的位置
  mapper-locations: classpath*:com/example/dao/mapper/*.xml
server:
   port: 8081
   context-path: /base-example/